# Generated by Django 2.2.7 on 2020-03-22 20:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FootageHandler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FileField', models.FileField(upload_to='mediaLib/')),
                ('FileDate', models.DateTimeField(auto_now_add=True)),
                ('FileDescriptor', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Files',
            },
        ),
        migrations.CreateModel(
            name='FriendlyFacesHandler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=100)),
                ('AutoUnlock', models.BooleanField(default=False)),
                ('FileField', models.FileField(upload_to='mediaLib/')),
            ],
            options={
                'verbose_name_plural': 'FriendlyFaces',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PhoneNumber', models.TextField(blank=True, max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
