# Generated by Django 2.2.7 on 2020-03-25 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20200322_2124'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alerthandler',
            old_name='FootageLink',
            new_name='MessageType',
        ),
        migrations.RemoveField(
            model_name='friendlyfaceshandler',
            name='FileField',
        ),
    ]
