# Generated by Django 2.2.7 on 2020-03-25 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('footage', '0004_friendlyfaceshandler'),
        ('footage', '0003_auto_20200322_2043'),
    ]

    operations = [
    ]
